# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MK_Text_iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'SnapKit', '~> 4.0.0'    

  # Pods for MK_Text_iOS

end

target 'MK_Text_OSX' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SnapKit', '~> 4.0.0'    

  # Pods for MK_Text_OSX

end
